dataclean_task:
  description: >
    You are tasked with generating the Python code, and executing it to read input dataset, perform data cleanup and write output dataset. 
    You are given the following information:

    - Dataset: <dataset_location> {datapath_info} </dataset_location>  
    - Output folder path: <cleandata_location> {cleandata_path} </cleandata_location>  

    Steps to Follow:

    1. Must follow the guidelines below strictly to generate the code.
       - The code should use pandas, numpy, matplotlib, seaborn, statsmodel and scikit-learn libraries.
       - Include the above libraries and any other library that may be required.
       - Load the input dataset from the dataset_location given below: 
         <dataset_location> {datapath_info} </dataset_location>  

    2. Data Understanding:
       Generate code to thoroughly examine the dataset and execute.
       Identify the data types of each column, the presence of missing values, outliers, and any inconsistencies.
       Provide a brief summary of your initial observations, including data quality issues. Just print the stats, no need to generate charts or figures.

    3. Data Cleaning:
       Generate code for the following to generate the cleaned dataset:
       - Missing Values: Handle missing values using appropriate techniques (e.g., imputation, deletion), justifying your choices.
       - Data Type Correction: Ensure all columns have the correct data types. Convert data as necessary.
       - Outlier Handling: Identify and address outliers using appropriate methods (e.g., capping, removal), documenting your approach.
       - Data Consistency: Standardize data formats (e.g., dates, text). Correct any inconsistencies or errors.
       - Duplicate Removal: Remove or handle duplicate entries.
       - Data Validation: Validate that all data is within acceptable ranges and conforms to expected patterns.

    4. Data Writing:
       After above steps are done, the code should write the cleaned dataset in the CSV format.
       The output data should be written to the:
         Output folder path: <cleandata_location> {cleandata_path} </cleandata_location>  

    5. The generated code satisfies the following conditions. If answer to any of the following is no, then the code generated is invalid:
       - Is dataset loaded from the <dataset_location> specified above?
       - Is the code writing the output data to the <cleandata_location>?

    6. Execute the code using the appropriate tool.

  agent: data_cleaner
  expected_output: >
    ### Output path
    - The path where the cleaned dataset is written.
    ### Code
    - The code provided in the context as it is, without any changes. Embed the code in fenced code blocks.
    ### Code Output
    - Outputs from code execution.
